### ISSUE TITLE
New Install google_apis location

### ISSUE THREAD

**Issue by gaz2030** [newbit1/rootAVD#79] opened 2023-06-24 02:33 UTC
Hi after a new install of Windows and Android Studio when running any rootAVD.bat command I am greeted with the Usage/Arguments command. Not sure but looking through the folder locations after running

rootAVD.bat %LOCALAPPDATA%\Android\Sdk\system-images\android-33\google_apis\x86_64\ramdisk.img

Even running rootAVD.bat ListAllAVDs brings up Usage/Arguments 
it looks like google_apis_playstore is no longer used and it is just google_apis

**Comment by newbit1** [comment] 2023-06-24 05:57
Hi, can you please copy your cmd output after rootavd.bat?

You dont have to use the localappdata env var anymore, this has changed due the android_home env var.

See the command examples

**Comment by gaz2030** [comment] 2023-06-24 06:08
C:\Users\gaz20\Downloads\rootAVD-master\rootAVD-master>rootAVD.bat
rootAVD A Script to root AVD by NewBit XDA

Usage:  rootAVD [DIR/ramdisk.img] [OPTIONS] | [EXTRA_CMDS]
or:     rootAVD [ARGUMENTS]

Arguments:
        ListAllAVDs                     Lists Command Examples for ALL installed AVDs

        InstallApps                     Just install all APKs placed in the Apps folder

Main operation mode:
        DIR                             a path to an AVD system-image
                                        - must always be the 1st Argument after rootAVD

ADB Path | Ramdisk DIR| ANDROID_HOME:
        [M]ac/Darwin:                   export PATH=~/Library/Android/sdk/platform-tools:\$PATH
                                        ~/Library/Android/sdk/system-images/android-\$API/google_apis_playstore/x86_64/

        [L]inux:                        export PATH=~/Android/Sdk/platform-tools:\$PATH
                                        ~/Android/Sdk/system-images/android-\$API/google_apis_playstore/x86_64/

        [W]indows:                      set PATH=%LOCALAPPDATA%\Android\Sdk\platform-tools;%PATH%
                                        system-images\android-$API\google_apis_playstore\x86_64\

                ANDROID_HOME:           By default, the script uses %LOCALAPPDATA%, to set its Android Home directory and
                                        search for AVD system-images and ADB binarys. This behaviour can be overwritten by setting
                                        the ANDROID_HOME variable. e.g. set ANDROID_HOME=%USERPROFILE%\Downloads\sdk

        $API:                           25,29,30,31,32,33,34,UpsideDownCake,etc.

Options:
        restore                         restore all existing .backup files, but doesn't delete them
                                        - the AVD doesn't need to be running
                                        - no other Argument after will be processed

        InstallKernelModules            install custom build kernel and its modules into ramdisk.img
                                        - kernel (bzImage) and its modules (initramfs.img) are inside rootAVD
                                        - both files will be deleted after installation

        InstallPrebuiltKernelModules    download and install an AOSP prebuilt kernel and its modules into ramdisk.img
                                        - similar to InstallKernelModules, but the AVD needs to be online

Options are exclusive, only one at the time will be processed.

Extra Arguments:
        DEBUG                           Debugging Mode, prevents rootAVD to pull back any patched file

        PATCHFSTAB                      fstab.ranchu will get patched to automount Block Devices like /dev/block/sda1
                                        - other entries can be added in the script as well
                                        - a custom build Kernel might be necessary

        GetUSBHPmodZ                    The USB HOST Permissions Module Zip will be downloaded into /sdcard/Download

        FAKEBOOTIMG                     Creates a fake Boot.img file that can directly be patched from the Magisk APP
                                        - Magisk will be launched to patch the fake Boot.img within 60s
                                        - the fake Boot.img will be placed under /sdcard/Download/fakeboot.img

Extra Arguments can be combined, there is no particular order.

Notes: rootAVD will
- always create .backup files of ramdisk*.img and kernel-ranchu
- replace both when done patching
- show a Menu, to choose the Magisk Version (Stable || Canary || Alpha), if the AVD is online
- make the choosen Magisk Version to its local
- install all APKs placed in the Apps folder
- use %LOCALAPPDATA%\Android\Sdk to search for AVD system images

Command Examples:
rootAVD.bat
rootAVD.bat ListAllAVDs
rootAVD.bat InstallApps

rootAVD.bat system-images\android-33\google_apis_playstore\x86_64\ramdisk.img
rootAVD.bat system-images\android-33\google_apis_playstore\x86_64\ramdisk.img FAKEBOOTIMG
rootAVD.bat system-images\android-33\google_apis_playstore\x86_64\ramdisk.img DEBUG PATCHFSTAB GetUSBHPmodZ
rootAVD.bat system-images\android-33\google_apis_playstore\x86_64\ramdisk.img restore
rootAVD.bat system-images\android-33\google_apis_playstore\x86_64\ramdisk.img InstallKernelModules
rootAVD.bat system-images\android-33\google_apis_playstore\x86_64\ramdisk.img InstallPrebuiltKernelModules
rootAVD.bat system-images\android-33\google_apis_playstore\x86_64\ramdisk.img InstallPrebuiltKernelModules GetUSBHPmodZ PATCHFSTAB DEBUG

**Comment by newbit1** [comment] 2023-06-24 08:04
Can you please give me the download link to this AVD image?
You will get this when you download it the first time over SDK Manager.
Perhaps you have to delete first, in order to be able to re-download it.

I have the same AVD, but I don't get this issue of yours. It seem, a busboy command
that is used in the Get Flaqs routine uses a busybox command that crashes on your AVD,
but not on mine.

**Comment by gaz2030** [comment] 2023-06-24 11:14
Preparing "Install SDK Patch Applier v4 (revision: 1)".
Downloading https://dl.google.com/android/repository/3534162-studio.sdk-patcher.zip
"Install SDK Patch Applier v4 (revision: 1)" ready.
Installing SDK Patch Applier v4 in C:\Users\gaz20\AppData\Local\Android\Sdk\patcher\v4
"Install SDK Patch Applier v4 (revision: 1)" complete.
"Install SDK Patch Applier v4 (revision: 1)" finished.
Preparing "Install Android Emulator (revision: 32.1.13)".
Downloading https://dl.google.com/android/repository/emulator-windows_x64-10086546.zip
"Install Android Emulator (revision: 32.1.13)" ready.
Installing Android Emulator in C:\Users\gaz20\AppData\Local\Android\Sdk\emulator
"Install Android Emulator (revision: 32.1.13)" complete.
"Install Android Emulator (revision: 32.1.13)" finished.
Preparing "Install Google APIs Intel x86_64 Atom System Image (revision: 6)".
Downloading https://dl.google.com/android/repository/sys-img/google_apis/x86_64-34_r06.zip
"Install Google APIs Intel x86_64 Atom System Image (revision: 6)" ready.
Installing Google APIs Intel x86_64 Atom System Image in C:\Users\gaz20\AppData\Local\Android\Sdk\system-images\android-34\google_apis\x86_64
"Install Google APIs Intel x86_64 Atom System Image (revision: 6)" complete.
"Install Google APIs Intel x86_64 Atom System Image (revision: 6)" finished.
Preparing "Install Android Emulator hypervisor driver (installer) (revision: 2.0.0)".
Downloading https://dl.google.com/android/repository/gvm-windows_v2_0_0.zip
"Install Android Emulator hypervisor driver (installer) (revision: 2.0.0)" ready.
Installing Android Emulator hypervisor driver (installer) in C:\Users\gaz20\AppData\Local\Android\Sdk\extras\google\Android_Emulator_Hypervisor_Driver
"Install Android Emulator hypervisor driver (installer) (revision: 2.0.0)" complete.
"Install Android Emulator hypervisor driver (installer) (revision: 2.0.0)" finished.
Preparing "Install Intel x86 Emulator Accelerator (HAXM installer) (revision: 7.6.5)".
Downloading https://dl.google.com/android/repository/extras/intel/haxm-windows_v7_6_5.zip
"Install Intel x86 Emulator Accelerator (HAXM installer) (revision: 7.6.5)" ready.
Installing Intel x86 Emulator Accelerator (HAXM installer) in C:\Users\gaz20\AppData\Local\Android\Sdk\extras\intel\Hardware_Accelerated_Execution_Manager
"Install Intel x86 Emulator Accelerator (HAXM installer) (revision: 7.6.5)" complete.
"Install Intel x86 Emulator Accelerator (HAXM installer) (revision: 7.6.5)" finished.
Preparing "Install Android SDK Platform 34 (revision: 1)".
Downloading https://dl.google.com/android/repository/platform-34-ext7_r01.zip
"Install Android SDK Platform 34 (revision: 1)" ready.
Installing Android SDK Platform 34 in C:\Users\gaz20\AppData\Local\Android\Sdk\platforms\android-34
"Install Android SDK Platform 34 (revision: 1)" complete.
"Install Android SDK Platform 34 (revision: 1)" finished.
Preparing "Install Android SDK Build-Tools 34 (revision: 34.0.0)".
Downloading https://dl.google.com/android/repository/build-tools_r34-windows.zip
"Install Android SDK Build-Tools 34 (revision: 34.0.0)" ready.
Installing Android SDK Build-Tools 34 in C:\Users\gaz20\AppData\Local\Android\Sdk\build-tools\34.0.0
"Install Android SDK Build-Tools 34 (revision: 34.0.0)" complete.
"Install Android SDK Build-Tools 34 (revision: 34.0.0)" finished.
Preparing "Install Android SDK Platform-Tools (revision: 34.0.3)".
Downloading https://dl.google.com/android/repository/platform-tools_r34.0.3-windows.zip
"Install Android SDK Platform-Tools (revision: 34.0.3)" ready.
Installing Android SDK Platform-Tools in C:\Users\gaz20\AppData\Local\Android\Sdk\platform-tools
"Install Android SDK Platform-Tools (revision: 34.0.3)" complete.
"Install Android SDK Platform-Tools (revision: 34.0.3)" finished.
Parsing C:\Users\gaz20\AppData\Local\Android\Sdk\build-tools\34.0.0\package.xml
Parsing C:\Users\gaz20\AppData\Local\Android\Sdk\emulator\package.xml
Parsing C:\Users\gaz20\AppData\Local\Android\Sdk\extras\google\Android_Emulator_Hypervisor_Driver\package.xml
Parsing C:\Users\gaz20\AppData\Local\Android\Sdk\extras\intel\Hardware_Accelerated_Execution_Manager\package.xml
Parsing C:\Users\gaz20\AppData\Local\Android\Sdk\patcher\v4\package.xml
Parsing C:\Users\gaz20\AppData\Local\Android\Sdk\platform-tools\package.xml
Parsing C:\Users\gaz20\AppData\Local\Android\Sdk\platforms\android-34\package.xml
Parsing C:\Users\gaz20\AppData\Local\Android\Sdk\system-images\android-34\google_apis\x86_64\package.xml
Android SDK is up to date.
Running Intel® HAXM installer
Intel HAXM reinstalled successfully!
Running Android Emulator Hypervisor Driver installer

SERVICE_NAME: gvm 
        TYPE               : 1  KERNEL_DRIVER  
        STATE              : 1  STOPPED 
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
[SC] DeleteService SUCCESS

SERVICE_NAME: gvm 
        TYPE               : 1  KERNEL_DRIVER  
        STATE              : 4  RUNNING 
                                (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
        PID                : 0
        FLAGS              : 
Creating Android virtual device
Android virtual device Pixel_3a_API_34_extension_level_7_x86_64 was successfully created

**Comment by gaz2030** [comment] 2023-06-24 11:16
I also tried 33
Packages to install: - Google APIs Intel x86_64 Atom System Image (system-images;android-33;google_apis;x86_64)
Preparing "Install Google APIs Intel x86_64 Atom System Image (revision: 12)".
Downloading https://dl.google.com/android/repository/sys-img/google_apis/x86_64-33_r12.zip

**Comment by newbit1** [comment] 2023-06-24 11:37
Thanks, but there is not the PlayStore Image within, only Google Apis.

**Comment by gaz2030** [comment] 2023-06-24 12:00
i just tried on linux, and came up with the same busybox error. Then I used an older fork https://github.com/bulutg/rootAVD and it worked.

**Comment by newbit1** [comment] 2023-06-24 12:07
Ok, this doesnt relly help to fix the issue. But good to know

**Comment by gaz2030** [comment] 2023-06-25 08:46
I might have run rootAVD it in early stages of boot. I will try again and see if I can get it to work.

**Comment by newbit1** [comment] 2023-06-25 09:16
Thanks, idealy i can reproduce the issue, so i can really fix it.

**Comment by newbit1** [comment] 2023-06-27 21:36
Thanks, but still, doesn't help finding the cause of that issue.
I might have found it though, should be fixed now. Please try it and report back.

**Closed** 2023-07-08 18:29 UTC
