### ISSUE TITLE
arithmetic syntax error

### ISSUE THREAD

**Issue by dikkedev** [newbit1/rootAVD#48] opened 2022-12-05 20:31 UTC
Tried with latest magisk version and v24.3

**/data/data/com.android.shell/Magisk/rootAVD.sh: line 1300: arithmetic syntax error**

```
[!] and we are NOT in an emulator shell
[*] Set Directorys
[-] Test if ADB SHELL is working
[-] In any AVD via ADB, you can execute code without root in /data/data/com.android.shell
[*] Cleaning up the ADB working space
[*] Creating the ADB working space
[-] Magisk installer Zip exists already
[*] Push Magisk.zip into /data/data/com.android.shell/Magisk
[-] ./Magisk.zip: 1 file pushed, 0 skipped. 426.2 MB/s (10878069 bytes in 0.024s)
[-] ramdisk.img Backup exists already
[*] Push ramdisk.img into /data/data/com.android.shell/Magisk
[-] /home/kiko/Android/Sdk/system-images/android-31/google_apis/x86_64/ramdisk.img: 1 file pushed, 0 skipped. 496.5 MB/s (3685297 bytes in 0.007s)
[*] Push rootAVD.sh into /data/data/com.android.shell/Magisk
[-] rootAVD.sh: 1 file pushed, 0 skipped. 226.4 MB/s (7855770 bytes in 0.033s)
[-] run the actually Boot/Ramdisk/Kernel Image Patch Script
[*] from Magisk by topjohnwu and modded by NewBit XDA
[!] We are in a ranchu emulator shell
[-] Api Level Arch Detect
[-] Device Platform is x64 only
[-] Device SDK API: 31
[-] First API Level: 31
[-] The AVD runs on Android 12
[-] Switch to the location of the script file
[*] Extracting busybox and Magisk.zip ...
[-] Checking AVDs Internet connection...
[!] AVD is online
[!] Checking available Magisk Versions
[?] Choose a Magisk Version to install and make it local
[s] (s)how all available Magisk Versions
[1] local stable '24.3' (ENTER)
[2] stable 25.2
[3] canary a468fd94(25205)
[4] alpha 44643ad7-alpha(25205)
1
[-] You choose Magisk local stable Version '24.3'
[*] Re-Run rootAVD in Magisk Busybox STANDALONE (D)ASH
[-] We are now in Magisk Busybox STANDALONE (D)ASH
[*] rootAVD with Magisk '24.3' Installer
[-] Get Flags
[*] System-as-root, keep dm/avb-verity
[-] Encrypted data, keep forceencrypt
[*] RECOVERYMODE=false
[-] KEEPVERITY=true
[*] KEEPFORCEENCRYPT=true
[-] copy all x86_64 files from /data/data/com.android.shell/Magisk/lib/x86_64 to /data/data/com.android.shell/Magisk
[*] Detecting ramdisk.img compression
[!] Ramdisk.img uses lz4_legacy compression
[-] taken from shakalaca's MagiskOnEmulator/process.sh
[*] executing ramdisk splitting / extraction / repacking
[-] API level greater then 30
[*] Check if we need to repack ramdisk before patching ..
[-] Multiple cpio archives detected
[*] Unpacking ramdisk ..
[*] Searching for the real End of the 1st Archive
[-] Dumping from 0 to 1691780 ..
Detected format: [lz4_legacy]
[-] Dumping from 1691780 to 3685278 ..
Detected format: [lz4_legacy]
/data/data/com.android.shell/Magisk/rootAVD.sh: line 1300: arithmetic syntax error

```

**Comment by newbit1** [comment] 2022-12-05 21:07
Hi,

```
[1] local stable '24.3' (ENTER)
[2] stable 25.2
[3] canary a468fd94(25205)
[4] alpha 44643ad7-alpha(25205)
1
[-] You choose Magisk local stable Version '24.3'
```
`[2] stable 25.2` is the newest magisk version, not 24.3.
It seems you are using an older script. try to redownload it. 25.2 is the local version in the present script.

Also,
```
[-] /home/kiko/Android/Sdk/system-images/android-31/google_apis/x86_64/ramdisk.img
```
if you are using an AVD without Play Store, you don't need magisk to get root.

But it's true, with this AVD version the issue
```
/data/data/com.android.shell/Magisk/rootAVD.sh: line 1300: arithmetic syntax error
```
can be reproduced. I will have a deeper look into this.
Thanks for pointing it out.

**Comment by newbit1** [comment] 2022-12-05 21:48
Issue is fixed now, please try again and report back.

**Comment by dikkedev** [comment] 2022-12-06 19:13
Please don't embed the busybox binaries in the rootAVD.sh file, why did you do that if may ask?

**Comment by newbit1** [comment] 2022-12-06 21:51
Because I wanted to have the swiss army knife in my pocket...
And as separated files. It is not just one busybox, they are a couple different busybox versions for each arch in it.
People have made PRs before, and I don't know why github is showing the script as binary. I can't change that.
If you know a way, please show me.

**Closed** 2022-12-08 10:03 UTC
